name: Lint & Format Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Prettier Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint frontend/ backend/ --ext .js,.ts,.jsx,.tsx

      - name: Run Prettier Check
        run: npx prettier --check "frontend/**/*.{js,jsx,ts,tsx,json,css,md}" "backend/**/*.{js,jsx,ts,tsx,json,css,md}"
