name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to process'
        required: false
      triggered_by:
        description: 'User who triggered this workflow'
        required: false

permissions:
  contents: read
  pull-requests: write
  issues: write
  actions: read

jobs:
  label:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Label Pull Request
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          sync-labels: true
