name: Lint & Format Check

on:
  pull_request:
    branches: [main]

jobs:
  lint-js:
    name: Lint JavaScript/TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - name: Run ESLint
        run: npx eslint frontend/ --ext .js,.ts,.jsx,.tsx
      - name: Run Prettier Check
        run: npx prettier --check frontend/

  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8
      - name: Run Black
        run: black --check backend/
      - name: Run Flake8
        run: flake8 backend/
