name: Stale Issues Bot

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  stale-issues:
    name: Manage Stale Issues
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read

    steps:
      - name: Mark stale issues and pull requests
        uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Configuration
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          close-issue-label: 'closed-by-stale-bot'
          close-pr-label: 'closed-by-stale-bot'
          
          # Timing configuration
          days-before-stale: 60
          days-before-close: 30
          
          # Issue configuration
          stale-issue-message: |
            ## 🕐 This issue has been marked as stale

            This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

            ### What does this mean?
            - This issue hasn't been updated in the last **60 days**
            - If you're still experiencing this issue, please add a comment or update the issue
            - If this issue is no longer relevant, you can close it yourself

            ### Next steps:
            - **Still relevant?** Add a comment explaining the current status
            - **Fixed?** Close the issue with a comment explaining the solution
            - **No longer needed?** Close the issue with a brief explanation

            ---
            *This message was automatically generated by the Stale Issues Bot. If you have any questions, please contact the maintainers.*

          close-issue-message: |
            ## 🔒 This issue has been closed due to inactivity

            This issue has been automatically closed because it has been marked as stale for **30 days** without any activity.

            ### What happened?
            - This issue was marked as stale **30 days ago**
            - No comments or updates were made during this period
            - The issue has been automatically closed to keep the repository clean

            ### Can this be reopened?
            Yes! If this issue is still relevant, you can:
            - **Reopen the issue** and add a comment explaining why it's still needed
            - **Create a new issue** with updated information
            - **Contact the maintainers** if you need assistance

            ---
            *This message was automatically generated by the Stale Issues Bot. If you have any questions, please contact the maintainers.*

          # Pull request configuration
          stale-pr-message: |
            ## 🕐 This pull request has been marked as stale

            This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

            ### What does this mean?
            - This PR hasn't been updated in the last **60 days**
            - If you're still working on this PR, please add a comment or push new commits
            - If this PR is no longer needed, you can close it yourself

            ### Next steps:
            - **Still working on it?** Add a comment with your progress or push new commits
            - **Ready for review?** Request a review from maintainers
            - **No longer needed?** Close the PR with a brief explanation

            ---
            *This message was automatically generated by the Stale Issues Bot. If you have any questions, please contact the maintainers.*

          close-pr-message: |
            ## 🔒 This pull request has been closed due to inactivity

            This pull request has been automatically closed because it has been marked as stale for **30 days** without any activity.

            ### What happened?
            - This PR was marked as stale **30 days ago**
            - No comments or updates were made during this period
            - The PR has been automatically closed to keep the repository clean

            ### Can this be reopened?
            Yes! If this PR is still relevant, you can:
            - **Reopen the PR** and add a comment explaining why it's still needed
            - **Create a new PR** with updated changes
            - **Contact the maintainers** if you need assistance

            ---
            *This message was automatically generated by the Stale Issues Bot. If you have any questions, please contact the maintainers.*

          # Labels to exempt from stale process
          exempt-issue-labels: 'priority:high,priority:critical,bug,security,good first issue,help wanted'
          exempt-pr-labels: 'priority:high,priority:critical,security,ready for review'
          
          # Only process issues and PRs
          only-issue-labels: ''
          only-pr-labels: ''
          
          # Operations
          operations-per-run: 100
          remove-stale-when-updated: true
          remove-pr-stale-when-updated: true
          
          # Debugging
          debug-only: false
          ascending: false